/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modul9;

/**
 *
 * @author Cordovix-ME
 */
public class praktikum2 extends javax.swing.JFrame {

    /**
     * Creates new form praktikum2
     */
    public praktikum2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        sam = new javax.swing.JTextField();
        combox = new javax.swing.JComboBox<>();
        nam = new javax.swing.JTextField();
        har = new javax.swing.JTextField();
        ber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Tiket Pesawat Surabaya-Jakarta");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 20, 220, 30);

        sam.setEditable(false);
        getContentPane().add(sam);
        sam.setBounds(190, 190, 190, 30);

        combox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--  Pilih Maskapai Penerbangan Anda --", "Sriwijaya Air", "Batik Air", "Garuda Indonesia" }));
        combox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxActionPerformed(evt);
            }
        });
        getContentPane().add(combox);
        combox.setBounds(70, 60, 240, 20);

        nam.setEditable(false);
        getContentPane().add(nam);
        nam.setBounds(190, 100, 190, 30);

        har.setEditable(false);
        getContentPane().add(har);
        har.setBounds(190, 130, 190, 30);

        ber.setEditable(false);
        getContentPane().add(ber);
        ber.setBounds(190, 160, 190, 30);

        jLabel2.setText("Sampai");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 190, 70, 14);

        jLabel3.setText("Nama Maskapai");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 100, 90, 14);

        jLabel4.setText("Harga");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 130, 50, 14);

        jLabel5.setText("Berangkat");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 160, 80, 14);

        jLabel11.setText("Rp");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(170, 130, 20, 20);

        setBounds(0, 0, 416, 282);
    }// </editor-fold>//GEN-END:initComponents

    private void comboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxActionPerformed
        // TODO add your handling code here:
        if(combox.getSelectedItem().equals("Sriwijaya Air")){
           nam.setText("Sriwijaya Air");
           har.setText("971000");
           ber.setText("06:00");
           sam.setText("08:40");
	}
        else if(combox.getSelectedItem().equals("Batik Air")){
           nam.setText("Batik Air");
           har.setText("1081000");
           ber.setText("12:00");
           sam.setText("14:20");
	}
        else if(combox.getSelectedItem().equals("Garuda Indonesia")){
           nam.setText("Garuda Indonesia");
           har.setText("1450000");
           ber.setText("17:50");
           sam.setText("19:10");
	}
    }//GEN-LAST:event_comboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(praktikum2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(praktikum2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(praktikum2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(praktikum2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new praktikum2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ber;
    private javax.swing.JComboBox<String> combox;
    private javax.swing.JTextField har;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nam;
    private javax.swing.JTextField sam;
    // End of variables declaration//GEN-END:variables
}
